package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class CdVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer cdValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String cd;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD_ALIAS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String cdAlias;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD_VAL_ID
   *
   * @return the value of m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getCdValId() {
    return cdValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD_VAL_ID
   *
   * @param cdValId the value for m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCdValId(Integer cdValId) {
    this.cdValId = cdValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD_GRP_ID
   *
   * @return the value of m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD_GRP_ID
   *
   * @param cdGrpId the value for m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD
   *
   * @return the value of m_cd_val.CD
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getCd() {
    return cd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD
   *
   * @param cd the value for m_cd_val.CD
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCd(String cd) {
    this.cd = cd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD_ALIAS
   *
   * @return the value of m_cd_val.CD_ALIAS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getCdAlias() {
    return cdAlias;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD_ALIAS
   *
   * @param cdAlias the value for m_cd_val.CD_ALIAS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCdAlias(String cdAlias) {
    this.cdAlias = cdAlias;
  }
}
