package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class CdValLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val_lang.CD_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer cdValLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String nm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val_lang.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer cdValId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val_lang.CD_VAL_LANG_ID
   *
   * @return the value of m_cd_val_lang.CD_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getCdValLangId() {
    return cdValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val_lang.CD_VAL_LANG_ID
   *
   * @param cdValLangId the value for m_cd_val_lang.CD_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCdValLangId(Integer cdValLangId) {
    this.cdValLangId = cdValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val_lang.LANG_DIV
   *
   * @return the value of m_cd_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val_lang.LANG_DIV
   *
   * @param langDiv the value for m_cd_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLangDiv(Integer langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val_lang.NM
   *
   * @return the value of m_cd_val_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val_lang.NM
   *
   * @param nm the value for m_cd_val_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val_lang.CD_VAL_ID
   *
   * @return the value of m_cd_val_lang.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getCdValId() {
    return cdValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val_lang.CD_VAL_ID
   *
   * @param cdValId the value for m_cd_val_lang.CD_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setCdValId(Integer cdValId) {
    this.cdValId = cdValId;
  }
}
