package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class FacilityAttrValLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val_lang.FACILITY_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityAttrValLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val_lang.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val_lang.VAL
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String val;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val_lang.FACILITY_ATTR_VAL_LANG_ID
   *
   * @return the value of m_facility_attr_val_lang.FACILITY_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityAttrValLangId() {
    return facilityAttrValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val_lang.FACILITY_ATTR_VAL_LANG_ID
   *
   * @param facilityAttrValLangId the value for m_facility_attr_val_lang.FACILITY_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityAttrValLangId(Integer facilityAttrValLangId) {
    this.facilityAttrValLangId = facilityAttrValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val_lang.FACILITY_ATTR_VAL_ID
   *
   * @return the value of m_facility_attr_val_lang.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityAttrValId() {
    return facilityAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val_lang.FACILITY_ATTR_VAL_ID
   *
   * @param facilityAttrValId the value for m_facility_attr_val_lang.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityAttrValId(Integer facilityAttrValId) {
    this.facilityAttrValId = facilityAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val_lang.LANG_DIV
   *
   * @return the value of m_facility_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val_lang.LANG_DIV
   *
   * @param langDiv the value for m_facility_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val_lang.VAL
   *
   * @return the value of m_facility_attr_val_lang.VAL
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getVal() {
    return val;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val_lang.VAL
   *
   * @param val the value for m_facility_attr_val_lang.VAL
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setVal(String val) {
    this.val = val;
  }
}
