package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class FacilityGrpAttrGrpLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityGrpAttrGrpLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityGrpAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String nm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_LANG_ID
   *
   * @return the value of m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityGrpAttrGrpLangId() {
    return facilityGrpAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_LANG_ID
   *
   * @param facilityGrpAttrGrpLangId the value for
   *        m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityGrpAttrGrpLangId(Integer facilityGrpAttrGrpLangId) {
    this.facilityGrpAttrGrpLangId = facilityGrpAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_ID
   *
   * @return the value of m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityGrpAttrGrpId() {
    return facilityGrpAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_ID
   *
   * @param facilityGrpAttrGrpId the value for m_facility_grp_attr_grp_lang.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityGrpAttrGrpId(Integer facilityGrpAttrGrpId) {
    this.facilityGrpAttrGrpId = facilityGrpAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp_lang.LANG_DIV
   *
   * @return the value of m_facility_grp_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp_lang.LANG_DIV
   *
   * @param langDiv the value for m_facility_grp_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp_lang.NM
   *
   * @return the value of m_facility_grp_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp_lang.NM
   *
   * @param nm the value for m_facility_grp_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }
}
