package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class Layout extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.LAYOUT_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer layoutId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String nm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.TYPE
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String type;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.LAYOUT_ID
   *
   * @return the value of m_layout.LAYOUT_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getLayoutId() {
    return layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.LAYOUT_ID
   *
   * @param layoutId the value for m_layout.LAYOUT_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLayoutId(Integer layoutId) {
    this.layoutId = layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.NM
   *
   * @return the value of m_layout.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.NM
   *
   * @param nm the value for m_layout.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.TYPE
   *
   * @return the value of m_layout.TYPE
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.TYPE
   *
   * @param type the value for m_layout.TYPE
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }
}
