package com.melip.entity;

import com.melip.entity.common.AbstractEntity;


public class ScreenObj extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer screenObjId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer screenId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer layoutObjId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.ENTITY
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String entity;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.ATTR_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer attrId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer targetScreenId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.SCREEN_OBJ_ID
   *
   * @return the value of m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getScreenObjId() {
    return screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.SCREEN_OBJ_ID
   *
   * @param screenObjId the value for m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setScreenObjId(Integer screenObjId) {
    this.screenObjId = screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.SCREEN_ID
   *
   * @return the value of m_screen_obj.SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getScreenId() {
    return screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.SCREEN_ID
   *
   * @param screenId the value for m_screen_obj.SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setScreenId(Integer screenId) {
    this.screenId = screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.LAYOUT_OBJ_ID
   *
   * @return the value of m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getLayoutObjId() {
    return layoutObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.LAYOUT_OBJ_ID
   *
   * @param layoutObjId the value for m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLayoutObjId(Integer layoutObjId) {
    this.layoutObjId = layoutObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.ENTITY
   *
   * @return the value of m_screen_obj.ENTITY
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getEntity() {
    return entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.ENTITY
   *
   * @param entity the value for m_screen_obj.ENTITY
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setEntity(String entity) {
    this.entity = entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.ATTR_ID
   *
   * @return the value of m_screen_obj.ATTR_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getAttrId() {
    return attrId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.ATTR_ID
   *
   * @param attrId the value for m_screen_obj.ATTR_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setAttrId(Integer attrId) {
    this.attrId = attrId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.TARGET_SCREEN_ID
   *
   * @return the value of m_screen_obj.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getTargetScreenId() {
    return targetScreenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.TARGET_SCREEN_ID
   *
   * @param targetScreenId the value for m_screen_obj.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setTargetScreenId(Integer targetScreenId) {
    this.targetScreenId = targetScreenId;
  }
}
