package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class CdVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer cdValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.CD
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String cd;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String alias;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_cd_val.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer displayNum;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD_VAL_ID
   *
   * @return the value of m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getCdValId() {
    return cdValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD_VAL_ID
   *
   * @param cdValId the value for m_cd_val.CD_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setCdValId(Integer cdValId) {
    this.cdValId = cdValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD_GRP_ID
   *
   * @return the value of m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD_GRP_ID
   *
   * @param cdGrpId the value for m_cd_val.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.CD
   *
   * @return the value of m_cd_val.CD
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getCd() {
    return cd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.CD
   *
   * @param cd the value for m_cd_val.CD
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setCd(String cd) {
    this.cd = cd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.ALIAS
   *
   * @return the value of m_cd_val.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getAlias() {
    return alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.ALIAS
   *
   * @param alias the value for m_cd_val.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setAlias(String alias) {
    this.alias = alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_cd_val.DISPLAY_NUM
   *
   * @return the value of m_cd_val.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getDisplayNum() {
    return displayNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_cd_val.DISPLAY_NUM
   *
   * @param displayNum the value for m_cd_val.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setDisplayNum(Integer displayNum) {
    this.displayNum = displayNum;
  }
}
