package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityGrpAttrGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer facilityGrpAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp.FACILITY_GRP_ATTR_GRP_ID
   *
   * @return the value of m_facility_grp_attr_grp.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getFacilityGrpAttrGrpId() {
    return facilityGrpAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp.FACILITY_GRP_ATTR_GRP_ID
   *
   * @param facilityGrpAttrGrpId the value for m_facility_grp_attr_grp.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setFacilityGrpAttrGrpId(Integer facilityGrpAttrGrpId) {
    this.facilityGrpAttrGrpId = facilityGrpAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp.TYPE
   *
   * @return the value of m_facility_grp_attr_grp.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp.TYPE
   *
   * @param type the value for m_facility_grp_attr_grp.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_grp.CD_GRP_ID
   *
   * @return the value of m_facility_grp_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_grp.CD_GRP_ID
   *
   * @param cdGrpId the value for m_facility_grp_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }
}
