package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityFacilityGrpLinkAttrGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp.TYPE
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @return the value of
   *         m_facility_facility_grp_link_attr_grp.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkAttrGrpId() {
    return facilityFacilityGrpLinkAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @param facilityFacilityGrpLinkAttrGrpId the value for
   *        m_facility_facility_grp_link_attr_grp.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkAttrGrpId(Integer facilityFacilityGrpLinkAttrGrpId) {
    this.facilityFacilityGrpLinkAttrGrpId = facilityFacilityGrpLinkAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp.TYPE
   *
   * @return the value of m_facility_facility_grp_link_attr_grp.TYPE
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp.TYPE
   *
   * @param type the value for m_facility_facility_grp_link_attr_grp.TYPE
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp.CD_GRP_ID
   *
   * @return the value of m_facility_facility_grp_link_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp.CD_GRP_ID
   *
   * @param cdGrpId the value for m_facility_facility_grp_link_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }
}
