package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityAttrGrpLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp_lang.FACILITY_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityAttrGrpLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp_lang.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer facilityAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String nm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp_lang.FACILITY_ATTR_GRP_LANG_ID
   *
   * @return the value of m_facility_attr_grp_lang.FACILITY_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityAttrGrpLangId() {
    return facilityAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp_lang.FACILITY_ATTR_GRP_LANG_ID
   *
   * @param facilityAttrGrpLangId the value for m_facility_attr_grp_lang.FACILITY_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityAttrGrpLangId(Integer facilityAttrGrpLangId) {
    this.facilityAttrGrpLangId = facilityAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp_lang.FACILITY_ATTR_GRP_ID
   *
   * @return the value of m_facility_attr_grp_lang.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getFacilityAttrGrpId() {
    return facilityAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp_lang.FACILITY_ATTR_GRP_ID
   *
   * @param facilityAttrGrpId the value for m_facility_attr_grp_lang.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setFacilityAttrGrpId(Integer facilityAttrGrpId) {
    this.facilityAttrGrpId = facilityAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp_lang.LANG_DIV
   *
   * @return the value of m_facility_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp_lang.LANG_DIV
   *
   * @param langDiv the value for m_facility_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp_lang.NM
   *
   * @return the value of m_facility_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp_lang.NM
   *
   * @param nm the value for m_facility_attr_grp_lang.NM
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }
}
