package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityGrpAttrVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer facilityGrpAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val.FACILITY_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer facilityGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer facilityGrpAttrGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ATTR_VAL_ID
   *
   * @return the value of m_facility_grp_attr_val.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getFacilityGrpAttrValId() {
    return facilityGrpAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ATTR_VAL_ID
   *
   * @param facilityGrpAttrValId the value for m_facility_grp_attr_val.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setFacilityGrpAttrValId(Integer facilityGrpAttrValId) {
    this.facilityGrpAttrValId = facilityGrpAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ID
   *
   * @return the value of m_facility_grp_attr_val.FACILITY_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getFacilityGrpId() {
    return facilityGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ID
   *
   * @param facilityGrpId the value for m_facility_grp_attr_val.FACILITY_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setFacilityGrpId(Integer facilityGrpId) {
    this.facilityGrpId = facilityGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ATTR_GRP_ID
   *
   * @return the value of m_facility_grp_attr_val.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getFacilityGrpAttrGrpId() {
    return facilityGrpAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val.FACILITY_GRP_ATTR_GRP_ID
   *
   * @param facilityGrpAttrGrpId the value for m_facility_grp_attr_val.FACILITY_GRP_ATTR_GRP_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setFacilityGrpAttrGrpId(Integer facilityGrpAttrGrpId) {
    this.facilityGrpAttrGrpId = facilityGrpAttrGrpId;
  }
}
