package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityFacilityGrpLink extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityFacilityGrpLinkId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link.FACILITY_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @return the value of m_facility_facility_grp_link.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkId() {
    return facilityFacilityGrpLinkId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @param facilityFacilityGrpLinkId the value for
   *        m_facility_facility_grp_link.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityFacilityGrpLinkId(Integer facilityFacilityGrpLinkId) {
    this.facilityFacilityGrpLinkId = facilityFacilityGrpLinkId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link.FACILITY_ID
   *
   * @return the value of m_facility_facility_grp_link.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityId() {
    return facilityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link.FACILITY_ID
   *
   * @param facilityId the value for m_facility_facility_grp_link.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityId(Integer facilityId) {
    this.facilityId = facilityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link.FACILITY_GRP_ID
   *
   * @return the value of m_facility_facility_grp_link.FACILITY_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityGrpId() {
    return facilityGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link.FACILITY_GRP_ID
   *
   * @param facilityGrpId the value for m_facility_facility_grp_link.FACILITY_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityGrpId(Integer facilityGrpId) {
    this.facilityGrpId = facilityGrpId;
  }
}
