package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityGrpAttrValLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityGrpAttrValLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityGrpAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp_attr_val_lang.VAL
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String val;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_LANG_ID
   *
   * @return the value of m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityGrpAttrValLangId() {
    return facilityGrpAttrValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_LANG_ID
   *
   * @param facilityGrpAttrValLangId the value for
   *        m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityGrpAttrValLangId(Integer facilityGrpAttrValLangId) {
    this.facilityGrpAttrValLangId = facilityGrpAttrValLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_ID
   *
   * @return the value of m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityGrpAttrValId() {
    return facilityGrpAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_ID
   *
   * @param facilityGrpAttrValId the value for m_facility_grp_attr_val_lang.FACILITY_GRP_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityGrpAttrValId(Integer facilityGrpAttrValId) {
    this.facilityGrpAttrValId = facilityGrpAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val_lang.LANG_DIV
   *
   * @return the value of m_facility_grp_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val_lang.LANG_DIV
   *
   * @param langDiv the value for m_facility_grp_attr_val_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp_attr_val_lang.VAL
   *
   * @return the value of m_facility_grp_attr_val_lang.VAL
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getVal() {
    return val;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp_attr_val_lang.VAL
   *
   * @param val the value for m_facility_grp_attr_val_lang.VAL
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setVal(String val) {
    this.val = val;
  }
}
