package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityFacilityGrpLinkAttrVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkAttrGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_VAL_ID
   *
   * @return the value of
   *         m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkAttrValId() {
    return facilityFacilityGrpLinkAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_VAL_ID
   *
   * @param facilityFacilityGrpLinkAttrValId the value for
   *        m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_VAL_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkAttrValId(Integer facilityFacilityGrpLinkAttrValId) {
    this.facilityFacilityGrpLinkAttrValId = facilityFacilityGrpLinkAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @return the value of m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkId() {
    return facilityFacilityGrpLinkId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @param facilityFacilityGrpLinkId the value for
   *        m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkId(Integer facilityFacilityGrpLinkId) {
    this.facilityFacilityGrpLinkId = facilityFacilityGrpLinkId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @return the value of
   *         m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkAttrGrpId() {
    return facilityFacilityGrpLinkAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @param facilityFacilityGrpLinkAttrGrpId the value for
   *        m_facility_facility_grp_link_attr_val.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkAttrGrpId(Integer facilityFacilityGrpLinkAttrGrpId) {
    this.facilityFacilityGrpLinkAttrGrpId = facilityFacilityGrpLinkAttrGrpId;
  }
}
