package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityFacilityGrpLinkAttrGrpLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkAttrGrpLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer facilityFacilityGrpLinkAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_facility_grp_link_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String nm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_LANG_ID
   *
   * @return the value of
   *         m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkAttrGrpLangId() {
    return facilityFacilityGrpLinkAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_LANG_ID
   *
   * @param facilityFacilityGrpLinkAttrGrpLangId the value for
   *        m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkAttrGrpLangId(Integer facilityFacilityGrpLinkAttrGrpLangId) {
    this.facilityFacilityGrpLinkAttrGrpLangId = facilityFacilityGrpLinkAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @return the value of
   *         m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getFacilityFacilityGrpLinkAttrGrpId() {
    return facilityFacilityGrpLinkAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @param facilityFacilityGrpLinkAttrGrpId the value for
   *        m_facility_facility_grp_link_attr_grp_lang.FACILITY_FACILITY_GRP_LINK_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setFacilityFacilityGrpLinkAttrGrpId(Integer facilityFacilityGrpLinkAttrGrpId) {
    this.facilityFacilityGrpLinkAttrGrpId = facilityFacilityGrpLinkAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.LANG_DIV
   *
   * @return the value of m_facility_facility_grp_link_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.LANG_DIV
   *
   * @param langDiv the value for m_facility_facility_grp_link_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.NM
   *
   * @return the value of m_facility_facility_grp_link_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_facility_grp_link_attr_grp_lang.NM
   *
   * @param nm the value for m_facility_facility_grp_link_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }
}
