package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityAttrVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_val.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityAttrGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val.FACILITY_ATTR_VAL_ID
   *
   * @return the value of m_facility_attr_val.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityAttrValId() {
    return facilityAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val.FACILITY_ATTR_VAL_ID
   *
   * @param facilityAttrValId the value for m_facility_attr_val.FACILITY_ATTR_VAL_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityAttrValId(Integer facilityAttrValId) {
    this.facilityAttrValId = facilityAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val.FACILITY_ID
   *
   * @return the value of m_facility_attr_val.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityId() {
    return facilityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val.FACILITY_ID
   *
   * @param facilityId the value for m_facility_attr_val.FACILITY_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityId(Integer facilityId) {
    this.facilityId = facilityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_val.FACILITY_ATTR_GRP_ID
   *
   * @return the value of m_facility_attr_val.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityAttrGrpId() {
    return facilityAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_val.FACILITY_ATTR_GRP_ID
   *
   * @param facilityAttrGrpId the value for m_facility_attr_val.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityAttrGrpId(Integer facilityAttrGrpId) {
    this.facilityAttrGrpId = facilityAttrGrpId;
  }
}
