package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityAttrGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer facilityAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp.ALIAS
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private String alias;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp.FACILITY_ATTR_GRP_ID
   *
   * @return the value of m_facility_attr_grp.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getFacilityAttrGrpId() {
    return facilityAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp.FACILITY_ATTR_GRP_ID
   *
   * @param facilityAttrGrpId the value for m_facility_attr_grp.FACILITY_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setFacilityAttrGrpId(Integer facilityAttrGrpId) {
    this.facilityAttrGrpId = facilityAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp.ALIAS
   *
   * @return the value of m_facility_attr_grp.ALIAS
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public String getAlias() {
    return alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp.ALIAS
   *
   * @param alias the value for m_facility_attr_grp.ALIAS
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setAlias(String alias) {
    this.alias = alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp.TYPE
   *
   * @return the value of m_facility_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp.TYPE
   *
   * @param type the value for m_facility_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_attr_grp.CD_GRP_ID
   *
   * @return the value of m_facility_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_attr_grp.CD_GRP_ID
   *
   * @param cdGrpId the value for m_facility_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }
}
