package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class FacilityGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp.FACILITY_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer facilityGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_facility_grp.PUBLISH_STS
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private String publishSts;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp.FACILITY_GRP_ID
   *
   * @return the value of m_facility_grp.FACILITY_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getFacilityGrpId() {
    return facilityGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp.FACILITY_GRP_ID
   *
   * @param facilityGrpId the value for m_facility_grp.FACILITY_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setFacilityGrpId(Integer facilityGrpId) {
    this.facilityGrpId = facilityGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_facility_grp.PUBLISH_STS
   *
   * @return the value of m_facility_grp.PUBLISH_STS
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public String getPublishSts() {
    return publishSts;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_facility_grp.PUBLISH_STS
   *
   * @param publishSts the value for m_facility_grp.PUBLISH_STS
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setPublishSts(String publishSts) {
    this.publishSts = publishSts;
  }
}
