package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class Layout extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.LAYOUT_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private Integer layoutId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.ALIAS
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private String alias;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.NM
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private String nm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  private String type;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.LAYOUT_ID
   *
   * @return the value of m_layout.LAYOUT_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public Integer getLayoutId() {
    return layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.LAYOUT_ID
   *
   * @param layoutId the value for m_layout.LAYOUT_ID
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setLayoutId(Integer layoutId) {
    this.layoutId = layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.ALIAS
   *
   * @return the value of m_layout.ALIAS
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public String getAlias() {
    return alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.ALIAS
   *
   * @param alias the value for m_layout.ALIAS
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setAlias(String alias) {
    this.alias = alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.NM
   *
   * @return the value of m_layout.NM
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.NM
   *
   * @param nm the value for m_layout.NM
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout.TYPE
   *
   * @return the value of m_layout.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout.TYPE
   *
   * @param type the value for m_layout.TYPE
   *
   * @mbggenerated Fri Jan 23 15:41:53 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }
}
