package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class LayoutObjGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer layoutObjGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj_grp.LAYOUT_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer layoutId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj_grp.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String alias;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj_grp.MULTIPLICITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String multiplicity;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @return the value of m_layout_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getLayoutObjGrpId() {
    return layoutObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @param layoutObjGrpId the value for m_layout_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLayoutObjGrpId(Integer layoutObjGrpId) {
    this.layoutObjGrpId = layoutObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj_grp.LAYOUT_ID
   *
   * @return the value of m_layout_obj_grp.LAYOUT_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getLayoutId() {
    return layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj_grp.LAYOUT_ID
   *
   * @param layoutId the value for m_layout_obj_grp.LAYOUT_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLayoutId(Integer layoutId) {
    this.layoutId = layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj_grp.ALIAS
   *
   * @return the value of m_layout_obj_grp.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getAlias() {
    return alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj_grp.ALIAS
   *
   * @param alias the value for m_layout_obj_grp.ALIAS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setAlias(String alias) {
    this.alias = alias;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj_grp.MULTIPLICITY
   *
   * @return the value of m_layout_obj_grp.MULTIPLICITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getMultiplicity() {
    return multiplicity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj_grp.MULTIPLICITY
   *
   * @param multiplicity the value for m_layout_obj_grp.MULTIPLICITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setMultiplicity(String multiplicity) {
    this.multiplicity = multiplicity;
  }
}
