package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class LayoutObj extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer layoutObjId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer layoutId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private String nm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_layout_obj.TYPE
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private String type;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj.LAYOUT_OBJ_ID
   *
   * @return the value of m_layout_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getLayoutObjId() {
    return layoutObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj.LAYOUT_OBJ_ID
   *
   * @param layoutObjId the value for m_layout_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setLayoutObjId(Integer layoutObjId) {
    this.layoutObjId = layoutObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj.LAYOUT_ID
   *
   * @return the value of m_layout_obj.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getLayoutId() {
    return layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj.LAYOUT_ID
   *
   * @param layoutId the value for m_layout_obj.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setLayoutId(Integer layoutId) {
    this.layoutId = layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj.NM
   *
   * @return the value of m_layout_obj.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj.NM
   *
   * @param nm the value for m_layout_obj.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_layout_obj.TYPE
   *
   * @return the value of m_layout_obj.TYPE
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_layout_obj.TYPE
   *
   * @param type the value for m_layout_obj.TYPE
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }
}
