package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class RegionAttrGrpLang extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp_lang.REGION_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer regionAttrGrpLangId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp_lang.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer regionAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String langDiv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String nm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp_lang.REGION_ATTR_GRP_LANG_ID
   *
   * @return the value of m_region_attr_grp_lang.REGION_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getRegionAttrGrpLangId() {
    return regionAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp_lang.REGION_ATTR_GRP_LANG_ID
   *
   * @param regionAttrGrpLangId the value for m_region_attr_grp_lang.REGION_ATTR_GRP_LANG_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setRegionAttrGrpLangId(Integer regionAttrGrpLangId) {
    this.regionAttrGrpLangId = regionAttrGrpLangId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp_lang.REGION_ATTR_GRP_ID
   *
   * @return the value of m_region_attr_grp_lang.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getRegionAttrGrpId() {
    return regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp_lang.REGION_ATTR_GRP_ID
   *
   * @param regionAttrGrpId the value for m_region_attr_grp_lang.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setRegionAttrGrpId(Integer regionAttrGrpId) {
    this.regionAttrGrpId = regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp_lang.LANG_DIV
   *
   * @return the value of m_region_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getLangDiv() {
    return langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp_lang.LANG_DIV
   *
   * @param langDiv the value for m_region_attr_grp_lang.LANG_DIV
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLangDiv(String langDiv) {
    this.langDiv = langDiv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp_lang.NM
   *
   * @return the value of m_region_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp_lang.NM
   *
   * @param nm the value for m_region_attr_grp_lang.NM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }
}
