package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class Region extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.REGION_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer regionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.HOME_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer homeScreenId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.PUBLISH_STS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String publishSts;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.REGION_ID
   *
   * @return the value of m_region.REGION_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getRegionId() {
    return regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.REGION_ID
   *
   * @param regionId the value for m_region.REGION_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setRegionId(Integer regionId) {
    this.regionId = regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.HOME_SCREEN_ID
   *
   * @return the value of m_region.HOME_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getHomeScreenId() {
    return homeScreenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.HOME_SCREEN_ID
   *
   * @param homeScreenId the value for m_region.HOME_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setHomeScreenId(Integer homeScreenId) {
    this.homeScreenId = homeScreenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.PUBLISH_STS
   *
   * @return the value of m_region.PUBLISH_STS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getPublishSts() {
    return publishSts;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.PUBLISH_STS
   *
   * @param publishSts the value for m_region.PUBLISH_STS
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setPublishSts(String publishSts) {
    this.publishSts = publishSts;
  }
}
