package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class RegionAttrGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer regionAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private String type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  private Integer cdGrpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp.REGION_ATTR_GRP_ID
   *
   * @return the value of m_region_attr_grp.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getRegionAttrGrpId() {
    return regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp.REGION_ATTR_GRP_ID
   *
   * @param regionAttrGrpId the value for m_region_attr_grp.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setRegionAttrGrpId(Integer regionAttrGrpId) {
    this.regionAttrGrpId = regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp.TYPE
   *
   * @return the value of m_region_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp.TYPE
   *
   * @param type the value for m_region_attr_grp.TYPE
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_grp.CD_GRP_ID
   *
   * @return the value of m_region_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public Integer getCdGrpId() {
    return cdGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_grp.CD_GRP_ID
   *
   * @param cdGrpId the value for m_region_attr_grp.CD_GRP_ID
   *
   * @mbggenerated Thu Feb 12 11:26:13 JST 2015
   */
  public void setCdGrpId(Integer cdGrpId) {
    this.cdGrpId = cdGrpId;
  }
}
