package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class Region extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.REGION_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer regionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.TEMPLATE_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private Integer templateId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region.PUBLISH_STS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  private String publishSts;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.REGION_ID
   *
   * @return the value of m_region.REGION_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getRegionId() {
    return regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.REGION_ID
   *
   * @param regionId the value for m_region.REGION_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setRegionId(Integer regionId) {
    this.regionId = regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.TEMPLATE_ID
   *
   * @return the value of m_region.TEMPLATE_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public Integer getTemplateId() {
    return templateId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.TEMPLATE_ID
   *
   * @param templateId the value for m_region.TEMPLATE_ID
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setTemplateId(Integer templateId) {
    this.templateId = templateId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region.PUBLISH_STS
   *
   * @return the value of m_region.PUBLISH_STS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public String getPublishSts() {
    return publishSts;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region.PUBLISH_STS
   *
   * @param publishSts the value for m_region.PUBLISH_STS
   *
   * @mbggenerated Thu Jan 08 18:12:08 JST 2015
   */
  public void setPublishSts(String publishSts) {
    this.publishSts = publishSts;
  }
}
