package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class RegionAttrVal extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_val.REGION_ATTR_VAL_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer regionAttrValId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_val.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer regionAttrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_region_attr_val.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer regionId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_val.REGION_ATTR_VAL_ID
   *
   * @return the value of m_region_attr_val.REGION_ATTR_VAL_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getRegionAttrValId() {
    return regionAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_val.REGION_ATTR_VAL_ID
   *
   * @param regionAttrValId the value for m_region_attr_val.REGION_ATTR_VAL_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setRegionAttrValId(Integer regionAttrValId) {
    this.regionAttrValId = regionAttrValId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_val.REGION_ATTR_GRP_ID
   *
   * @return the value of m_region_attr_val.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getRegionAttrGrpId() {
    return regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_val.REGION_ATTR_GRP_ID
   *
   * @param regionAttrGrpId the value for m_region_attr_val.REGION_ATTR_GRP_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setRegionAttrGrpId(Integer regionAttrGrpId) {
    this.regionAttrGrpId = regionAttrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_region_attr_val.REGION_ID
   *
   * @return the value of m_region_attr_val.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getRegionId() {
    return regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_region_attr_val.REGION_ID
   *
   * @param regionId the value for m_region_attr_val.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setRegionId(Integer regionId) {
    this.regionId = regionId;
  }
}
