package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;

public class ScreenObjGrp extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_grp.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  private Integer screenObjGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_grp.SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  private Integer screenId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  private Integer layoutObjGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_grp.ENTITY
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  private String entity;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_grp.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  private Integer targetScreenId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_grp.SCREEN_OBJ_GRP_ID
   *
   * @return the value of m_screen_obj_grp.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public Integer getScreenObjGrpId() {
    return screenObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_grp.SCREEN_OBJ_GRP_ID
   *
   * @param screenObjGrpId the value for m_screen_obj_grp.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public void setScreenObjGrpId(Integer screenObjGrpId) {
    this.screenObjGrpId = screenObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_grp.SCREEN_ID
   *
   * @return the value of m_screen_obj_grp.SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public Integer getScreenId() {
    return screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_grp.SCREEN_ID
   *
   * @param screenId the value for m_screen_obj_grp.SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public void setScreenId(Integer screenId) {
    this.screenId = screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @return the value of m_screen_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public Integer getLayoutObjGrpId() {
    return layoutObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @param layoutObjGrpId the value for m_screen_obj_grp.LAYOUT_OBJ_GRP_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public void setLayoutObjGrpId(Integer layoutObjGrpId) {
    this.layoutObjGrpId = layoutObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_grp.ENTITY
   *
   * @return the value of m_screen_obj_grp.ENTITY
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public String getEntity() {
    return entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_grp.ENTITY
   *
   * @param entity the value for m_screen_obj_grp.ENTITY
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public void setEntity(String entity) {
    this.entity = entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_grp.TARGET_SCREEN_ID
   *
   * @return the value of m_screen_obj_grp.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public Integer getTargetScreenId() {
    return targetScreenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_grp.TARGET_SCREEN_ID
   *
   * @param targetScreenId the value for m_screen_obj_grp.TARGET_SCREEN_ID
   *
   * @mbggenerated Thu Jan 29 10:58:24 JST 2015
   */
  public void setTargetScreenId(Integer targetScreenId) {
    this.targetScreenId = targetScreenId;
  }
}
