package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class ScreenObjAttr extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.SCREEN_OBJ_ATTR_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer screenObjAttrId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer screenObjId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.ENTITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private String entity;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer attrGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer displayNum;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj_attr.TARGET_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer targetScreenId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.SCREEN_OBJ_ATTR_ID
   *
   * @return the value of m_screen_obj_attr.SCREEN_OBJ_ATTR_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getScreenObjAttrId() {
    return screenObjAttrId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.SCREEN_OBJ_ATTR_ID
   *
   * @param screenObjAttrId the value for m_screen_obj_attr.SCREEN_OBJ_ATTR_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setScreenObjAttrId(Integer screenObjAttrId) {
    this.screenObjAttrId = screenObjAttrId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.SCREEN_OBJ_ID
   *
   * @return the value of m_screen_obj_attr.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getScreenObjId() {
    return screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.SCREEN_OBJ_ID
   *
   * @param screenObjId the value for m_screen_obj_attr.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setScreenObjId(Integer screenObjId) {
    this.screenObjId = screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.ENTITY
   *
   * @return the value of m_screen_obj_attr.ENTITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public String getEntity() {
    return entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.ENTITY
   *
   * @param entity the value for m_screen_obj_attr.ENTITY
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setEntity(String entity) {
    this.entity = entity;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.ATTR_GRP_ID
   *
   * @return the value of m_screen_obj_attr.ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getAttrGrpId() {
    return attrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.ATTR_GRP_ID
   *
   * @param attrGrpId the value for m_screen_obj_attr.ATTR_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setAttrGrpId(Integer attrGrpId) {
    this.attrGrpId = attrGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.DISPLAY_NUM
   *
   * @return the value of m_screen_obj_attr.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getDisplayNum() {
    return displayNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.DISPLAY_NUM
   *
   * @param displayNum the value for m_screen_obj_attr.DISPLAY_NUM
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setDisplayNum(Integer displayNum) {
    this.displayNum = displayNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj_attr.TARGET_SCREEN_ID
   *
   * @return the value of m_screen_obj_attr.TARGET_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getTargetScreenId() {
    return targetScreenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj_attr.TARGET_SCREEN_ID
   *
   * @param targetScreenId the value for m_screen_obj_attr.TARGET_SCREEN_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setTargetScreenId(Integer targetScreenId) {
    this.targetScreenId = targetScreenId;
  }
}
