package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class Screen extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen.SCREEN_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer screenId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer regionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private Integer layoutId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen.TARGET_ENTITY
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private String targetEntity;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  private String nm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen.SCREEN_ID
   *
   * @return the value of m_screen.SCREEN_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getScreenId() {
    return screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen.SCREEN_ID
   *
   * @param screenId the value for m_screen.SCREEN_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setScreenId(Integer screenId) {
    this.screenId = screenId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen.REGION_ID
   *
   * @return the value of m_screen.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getRegionId() {
    return regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen.REGION_ID
   *
   * @param regionId the value for m_screen.REGION_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setRegionId(Integer regionId) {
    this.regionId = regionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen.LAYOUT_ID
   *
   * @return the value of m_screen.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public Integer getLayoutId() {
    return layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen.LAYOUT_ID
   *
   * @param layoutId the value for m_screen.LAYOUT_ID
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setLayoutId(Integer layoutId) {
    this.layoutId = layoutId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen.TARGET_ENTITY
   *
   * @return the value of m_screen.TARGET_ENTITY
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public String getTargetEntity() {
    return targetEntity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen.TARGET_ENTITY
   *
   * @param targetEntity the value for m_screen.TARGET_ENTITY
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setTargetEntity(String targetEntity) {
    this.targetEntity = targetEntity;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen.NM
   *
   * @return the value of m_screen.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public String getNm() {
    return nm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen.NM
   *
   * @param nm the value for m_screen.NM
   *
   * @mbggenerated Mon Jan 19 17:51:49 JST 2015
   */
  public void setNm(String nm) {
    this.nm = nm;
  }
}
