package com.melip.webservices.entity;

import com.melip.webservices.entity.common.AbstractEntity;


public class ScreenObj extends AbstractEntity {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer screenObjId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer screenObjGrpId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  private Integer layoutObjId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.SCREEN_OBJ_ID
   *
   * @return the value of m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getScreenObjId() {
    return screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.SCREEN_OBJ_ID
   *
   * @param screenObjId the value for m_screen_obj.SCREEN_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setScreenObjId(Integer screenObjId) {
    this.screenObjId = screenObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.SCREEN_OBJ_GRP_ID
   *
   * @return the value of m_screen_obj.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getScreenObjGrpId() {
    return screenObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.SCREEN_OBJ_GRP_ID
   *
   * @param screenObjGrpId the value for m_screen_obj.SCREEN_OBJ_GRP_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setScreenObjGrpId(Integer screenObjGrpId) {
    this.screenObjGrpId = screenObjGrpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_screen_obj.LAYOUT_OBJ_ID
   *
   * @return the value of m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public Integer getLayoutObjId() {
    return layoutObjId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_screen_obj.LAYOUT_OBJ_ID
   *
   * @param layoutObjId the value for m_screen_obj.LAYOUT_OBJ_ID
   *
   * @mbggenerated Wed Jan 28 11:26:06 JST 2015
   */
  public void setLayoutObjId(Integer layoutObjId) {
    this.layoutObjId = layoutObjId;
  }
}
